security:
    encoders:
        "Application\Sonata\UserBundle\Entity\User":
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN]

        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
            - ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT

    providers:
        fos_userbundle:
            id: undf_reload_user_optimization.user_provider

        facebook_provider:
          id: undf.facebook_provider

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt|assetic)|css|images|js|comb)/
            security: false

        # This firewall is used to handle the admin login area
        # This part is handled by the Sonata User Bundle
        admin:
            pattern:      /admin(.*)
            context:        user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path: /admin/dashboard
            logout:
                path:   /admin/logout
                target:  /admin/login
            anonymous:    true

        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle
        main:
            pattern:      .*
            context:        user
            fos_facebook:
                app_url: "http://apps.facebook.com/sandbox/"
                server_url: "http://sandbox.local/"
                login_path: fos_user_security_login
                check_path: fb_security_check
                default_target_path: fos_user_profile_edit
                provider: facebook_provider
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    false
                check_path:     fos_user_security_check
                failure_path:   fos_user_security_login
                default_target_path: fos_user_profile_edit
#                success_handler: undf_user.component.authentication.handler.login_success_handler
            logout:
                  path:   fos_user_security_logout
                  target: fos_user_security_login
            anonymous:    true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/(es\/|en\/)?login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es\/|en\/)?register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es\/|en\/)?resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/locale, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: [ROLE_USER, ROLE_FACEBOOK] }

#    acl:
#        connection: default