fos_fb_user_security:
    resource: "facebook_routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

undf_locale_switcher:
    pattern: /locale/change/{_locale}
    defaults: { _controller: UndfUserBundle:Locale:switch, _locale: %locale% }
    options:
      reload: true

undf_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UndfUserBundle:Default:index }
