parameters:
  undf_user.event_listener.login.class: Undf\UserBundle\Listener\LoginListener
  undf_locale.session.variable: %lunetics_locale.session.variable%

services:
  undf_user.profile.form.type:
    class: Undf\UserBundle\Form\Type\ProfileFormType
    tags:
      - { name: form.type, alias: undf_user_profile }
    arguments: [ "%fos_user.model.user.class%" ]

  undf_user.change_password.form.type:
    class: Undf\UserBundle\Form\Type\ChangePasswordFormType
    tags:
      - { name: form.type, alias: undf_user_change_password }
    arguments: [ "%fos_user.model.user.class%" ]

  undf_user.registration.form.type:
    class: Undf\UserBundle\Form\Type\RegistrationFormType
    tags:
      - { name: form.type, alias: undf_user_registration }
    arguments: [ "%fos_user.model.user.class%" ]

  undf.facebook_provider:
    class: Undf\UserBundle\Security\User\Provider\FacebookProvider
    arguments:
      facebook: "@fos_facebook.api"
      userManager: "@fos_user.user_manager"
      validator: "@validator"

  security.validator.facebook_user_password:
    class: Undf\UserBundle\Validator\Constraint\FacebookUserPasswordValidator
    tags:
      - { name: validator.constraint_validator, alias: security.validator.facebook_user_password }
    arguments: [ "@security.context", "@security.encoder_factory"]

  undf_user.event_listener.login:
    class: %undf_user.event_listener.login.class%
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    arguments: [ "%undf_locale.session.variable%" ]

  undf_user.user_manager:
    class: Undf\UserBundle\Entity\UserManager
    arguments:
      - "@security.encoder_factory"
      - "@fos_user.util.username_canonicalizer"
      - "@fos_user.util.email_canonicalizer"
      - "@fos_user.entity_manager"
      - "%fos_user.model.user.class%"

