<?php

namespace Undf\PlanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageRepository extends EntityRepository
{

    public function findOneByCityName($name)
    {
        $query = $this->createQueryBuilder('s')
                ->select('s')
                ->join('s.city', 'c')
                ->where('c.name = :name')
                ->setParameter('name', $name)
                ->getQuery();
        return $query->getSingleResult();
    }

}
